# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  iridium.web:
    build:
      context: "/Users/fatihaydin/RiderProjects/iridium"
      dockerfile: "Iridium.Web/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "iridiumweb:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "/Users/fatihaydin/.nuget/packages:/root/.nuget/packages"
    - "/Users/fatihaydin/RiderProjects/iridium/Iridium.Web:/app:rw"
    - "/Users/fatihaydin/RiderProjects/iridium:/src:rw"
    - "/Users/fatihaydin/.local/share/JetBrains/RiderRemoteDebugger/2023.3.5/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/fatihaydin/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_6_02_17_12_41:/var/opt/rider-debugger:rw"
    working_dir: "/app"
